name: Multi-Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WEBHOOK_URL: https://myhook.com/ginie
      REPOS_FILE: repos.txt
      IGNORED_REPOS_FILE: repos.ignored

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load GitHub Token
      run: echo "export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: List repositories
      run: |
        bash ask.sh
