name: Multi-Repository Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      WEBHOOK_URL: https://myhook.com/ginie
      REPOS_FILE: repos.txt
      IGNORED_REPOS_FILE: repos.ignored

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Load GitHub Token
      run: echo "export GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV

    - name: Read repository list from file
      run: echo "REPOS=$(cat ${{ env.REPOS_FILE }})" >> $GITHUB_ENV

    - name: Read ignored repository list from file
      run: echo "IGNORED_REPOS=$(cat ${{ env.IGNORED_REPOS_FILE }})" >> $GITHUB_ENV


    - name: List repositories
      run: |
        # Access the list of repositories from the output variable
        echo "Repos: $REPOS"
        IFS=',' read -ra repositories <<< "$REPOS"
        echo "list: $repositories"
        IFS=',' read -ra ignored_repositories <<< "$IGNORED_REPOS"
        echo "ignored: $ignored_repositories"
        
        echo "Start asking\n"

        for repo in "${repositories[@]}"; do
          # Check if the repository is in the ignored list
          if [[ " ${ignored_repositories[@]} " =~ " $repo " ]]; then
            echo "Skipping $repo (listed in repo.ignored)"
          else
            echo "Checking out $repo"
            git clone "https://github.com/$repo.git"

            # Run your bash command in each repository
            repo_name=$(echo "$repo" | cut -d'/' -f2)
            bash ask.sh $repo_name
          fi
        done
